apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-dapr
  labels:
    app: subscriber-dapr
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber-dapr
  template:
    metadata:
      labels:
        app: subscriber-dapr
      annotations:
        # https://docs.dapr.io/reference/arguments-annotations-overview/
        dapr.io/enabled: "true"
        dapr.io/app-id: "subscriber-dapr"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
    spec:
      serviceAccountName: workload-identity-test
      containers:
      - name: subscriber-dapr
        image: $REGISTRY_NAME/subscriber-dapr:latest
        ports:
        - containerPort: 3000
        env:
          - name: QUEUE_NAME
            value: queue1
        imagePullPolicy: Always