apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  httpPipeline:
    handlers:
    - name: ratelimit
      type: middleware.http.ratelimit
  policies:
    # Retries are named templates for retry configurations and are instantiated for life of the operation.
    retries:
      pubsubRetry:
        policy: exponential
        maxInterval: 5m
        # maxRetries: 10
  targets:
    components:
      pubsub: 
        retry: pubsubRetry
      servicebus-pubsub:
        retry: pubsubRetry
